# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`

default_language_version:
  python: python3



repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-yaml
  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
    - id: flake8
    args: ['--extend-ignore=E999,F821,E402,E127']