# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`
ci:
  autofix_prs: true

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: test/data

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: dev-docs|docs|versioneer.py|RefRed/_version.py|create_graph.py|test/data
      args: ['--extend-ignore=E999,F821,E402,E127']