ci:
  autofix_prs: true
  skip: [pixi-lock-check]

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      #- id: check-added-large-files
      #  args: ['--maxkb=4096']
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        exclude: |
          docs
          refred/_version.py
          test/data
      - id: ruff-format
        exclude: |
          docs
          refred/_version.py
          test/data

  - repo: local
    hooks:
      - id: pixi-lock-check
        name: pixi-lock-check
        entry: bash -c "pixi lock --check"
        stage: pre-push
        language: system
