# https://docs.readthedocs.io/en/stable/guides/conda.html
# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-22.9"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: environment.yml
