name: refred
channels:
  - mantid/label/main
  - conda-forge
dependencies:
  - python=3.10.*
  - mantid=6.12.0
  - qt==5.15.8
  - pyqt>=5.15,<6
  - qtpy>=1.9.0
  - configobj
  - matplotlib
  - pydantic
  - pip
  - pip:
      - build
      - git+https://github.com/neutrons/LiquidsReflectometer.git@v2.1.13#egg=lr_reduction
  # documentation
  - sphinx
  - sphinx_rtd_theme
  # development
  - ruff
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-qt
