name: refred
channels:
  - mantid/label/main
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mantidworkbench>=6.7.0
  - qt>=5.12.9,<6
  - pyqt>=5.12.3
  - qtpy>=1.9.0
  - configobj
  - matplotlib
  - pip
  - pip:
    - git+https://github.com/neutrons/LiquidsReflectometer.git@v2.0.16#egg=lr_reduction
# documentation
  - sphinx
  - sphinx_rtd_theme
# development
  - black
  - flake8
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-qt

