[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/versioneer.py  # exclude file foo.py in the root of the project (in addition to the defaults)
'''
