[tool.ruff]
line-length = 120
extend-exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
  "versioneer.py",
  "test/data/*.py",
]

[tool.ruff.lint]
select = ["A", "ARG", "ASYNC", "BLE", "C90", "E", "F", "I", "N", "UP032", "W"]
ignore = ["F821", "E402"]

[tool.mypy]
ignore_missing_imports = true
allow_untyped_globals = true
# ignore = ["test/data"]
