name: test
channels:
- mantid
- conda-forge
dependencies:
- configobj
- flake8=3.9.2
- mantid=6.5.0
- matplotlib
- mypy
- pytest-cov
- pytest-qt
- qtpy<2
- pyqt=5.12
- pip:
  - git+https://github.com/neutrons/LiquidsReflectometer.git@v2.0.9#egg=lr_reduction
