# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sf_calculator_interface.ui'
#
# Created by: qtpy UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
from .mplwidgetxlog import MPLWidgetXLog
from .mplwidgetnolog import MPLWidgetNoLog

from qtpy import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_SFCalculatorInterface(object):
    def setupUi(self, SFCalculatorInterface):
        SFCalculatorInterface.setObjectName(_fromUtf8("SFCalculatorInterface"))
        SFCalculatorInterface.resize(1221, 776)
        self.centralwidget = QtWidgets.QWidget(SFCalculatorInterface)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1188, 942))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.runSequenceLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.runSequenceLineEdit.setText(_fromUtf8(""))
        self.runSequenceLineEdit.setObjectName(_fromUtf8("runSequenceLineEdit"))
        self.horizontalLayout_2.addWidget(self.runSequenceLineEdit)
        self.incidentMediumComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.incidentMediumComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.incidentMediumComboBox.setEditable(True)
        self.incidentMediumComboBox.setObjectName(_fromUtf8("incidentMediumComboBox"))
        self.incidentMediumComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.incidentMediumComboBox)
        self.toolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton.setEnabled(False)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.yt_plot = MPLWidgetNoLog(self.scrollAreaWidgetContents)
        self.yt_plot.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yt_plot.sizePolicy().hasHeightForWidth())
        self.yt_plot.setSizePolicy(sizePolicy)
        self.yt_plot.setObjectName(_fromUtf8("yt_plot"))
        self.horizontalLayout.addWidget(self.yt_plot)
        self.yi_plot = MPLWidgetXLog(self.scrollAreaWidgetContents)
        self.yi_plot.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yi_plot.sizePolicy().hasHeightForWidth())
        self.yi_plot.setSizePolicy(sizePolicy)
        self.yi_plot.setObjectName(_fromUtf8("yi_plot"))
        self.horizontalLayout.addWidget(self.yi_plot)
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_26.addItem(spacerItem)
        self.error_label = QtWidgets.QLabel(self.frame_11)
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.verticalLayout_26.addWidget(self.error_label)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.dataBackFromLabel = QtWidgets.QLabel(self.frame_11)
        self.dataBackFromLabel.setEnabled(False)
        self.dataBackFromLabel.setObjectName(_fromUtf8("dataBackFromLabel"))
        self.horizontalLayout_32.addWidget(self.dataBackFromLabel)
        self.dataBackToValue = QtWidgets.QSpinBox(self.frame_11)
        self.dataBackToValue.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.dataBackToValue.setPalette(palette)
        self.dataBackToValue.setMinimum(-1)
        self.dataBackToValue.setMaximum(255)
        self.dataBackToValue.setProperty("value", 255)
        self.dataBackToValue.setObjectName(_fromUtf8("dataBackToValue"))
        self.horizontalLayout_32.addWidget(self.dataBackToValue)
        self.back2_error = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.back2_error.setFont(font)
        self.back2_error.setAccessibleDescription(_fromUtf8(""))
        self.back2_error.setAlignment(QtCore.Qt.AlignCenter)
        self.back2_error.setObjectName(_fromUtf8("back2_error"))
        self.horizontalLayout_32.addWidget(self.back2_error)
        self.verticalLayout_28.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.dataPeakFromLabel = QtWidgets.QLabel(self.frame_11)
        self.dataPeakFromLabel.setEnabled(False)
        self.dataPeakFromLabel.setObjectName(_fromUtf8("dataPeakFromLabel"))
        self.horizontalLayout_33.addWidget(self.dataPeakFromLabel)
        self.dataPeakToValue = QtWidgets.QSpinBox(self.frame_11)
        self.dataPeakToValue.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.dataPeakToValue.setPalette(palette)
        self.dataPeakToValue.setMinimum(-1)
        self.dataPeakToValue.setMaximum(255)
        self.dataPeakToValue.setProperty("value", 255)
        self.dataPeakToValue.setObjectName(_fromUtf8("dataPeakToValue"))
        self.horizontalLayout_33.addWidget(self.dataPeakToValue)
        self.peak2_error = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.peak2_error.setFont(font)
        self.peak2_error.setAccessibleDescription(_fromUtf8(""))
        self.peak2_error.setAlignment(QtCore.Qt.AlignCenter)
        self.peak2_error.setObjectName(_fromUtf8("peak2_error"))
        self.horizontalLayout_33.addWidget(self.peak2_error)
        self.verticalLayout_28.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.dataPeakToLabel = QtWidgets.QLabel(self.frame_11)
        self.dataPeakToLabel.setEnabled(False)
        self.dataPeakToLabel.setObjectName(_fromUtf8("dataPeakToLabel"))
        self.horizontalLayout_34.addWidget(self.dataPeakToLabel)
        self.dataPeakFromValue = QtWidgets.QSpinBox(self.frame_11)
        self.dataPeakFromValue.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.dataPeakFromValue.setPalette(palette)
        self.dataPeakFromValue.setMinimum(-1)
        self.dataPeakFromValue.setMaximum(255)
        self.dataPeakFromValue.setProperty("value", 0)
        self.dataPeakFromValue.setObjectName(_fromUtf8("dataPeakFromValue"))
        self.horizontalLayout_34.addWidget(self.dataPeakFromValue)
        self.peak1_error = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.peak1_error.setFont(font)
        self.peak1_error.setAccessibleDescription(_fromUtf8(""))
        self.peak1_error.setAlignment(QtCore.Qt.AlignCenter)
        self.peak1_error.setObjectName(_fromUtf8("peak1_error"))
        self.horizontalLayout_34.addWidget(self.peak1_error)
        self.verticalLayout_28.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.dataBackToLabel = QtWidgets.QLabel(self.frame_11)
        self.dataBackToLabel.setEnabled(False)
        self.dataBackToLabel.setObjectName(_fromUtf8("dataBackToLabel"))
        self.horizontalLayout_35.addWidget(self.dataBackToLabel)
        self.dataBackFromValue = QtWidgets.QSpinBox(self.frame_11)
        self.dataBackFromValue.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.dataBackFromValue.setPalette(palette)
        self.dataBackFromValue.setMinimum(-1)
        self.dataBackFromValue.setMaximum(255)
        self.dataBackFromValue.setProperty("value", 0)
        self.dataBackFromValue.setObjectName(_fromUtf8("dataBackFromValue"))
        self.horizontalLayout_35.addWidget(self.dataBackFromValue)
        self.back1_error = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.back1_error.setFont(font)
        self.back1_error.setAccessibleDescription(_fromUtf8(""))
        self.back1_error.setAlignment(QtCore.Qt.AlignCenter)
        self.back1_error.setObjectName(_fromUtf8("back1_error"))
        self.horizontalLayout_35.addWidget(self.back1_error)
        self.verticalLayout_28.addLayout(self.horizontalLayout_35)
        self.dataBackgroundFlag = QtWidgets.QCheckBox(self.frame_11)
        self.dataBackgroundFlag.setEnabled(False)
        self.dataBackgroundFlag.setChecked(True)
        self.dataBackgroundFlag.setObjectName(_fromUtf8("dataBackgroundFlag"))
        self.verticalLayout_28.addWidget(self.dataBackgroundFlag)
        self.verticalLayout_26.addLayout(self.verticalLayout_28)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_26.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame_11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.dataTOFmanualLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dataTOFmanualLabel.setEnabled(False)
        self.dataTOFmanualLabel.setObjectName(_fromUtf8("dataTOFmanualLabel"))
        self.horizontalLayout_40.addWidget(self.dataTOFmanualLabel)
        self.frame_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setLineWidth(0)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.dataTOFautoMode = QtWidgets.QRadioButton(self.frame_14)
        self.dataTOFautoMode.setEnabled(False)
        self.dataTOFautoMode.setChecked(True)
        self.dataTOFautoMode.setAutoExclusive(True)
        self.dataTOFautoMode.setObjectName(_fromUtf8("dataTOFautoMode"))
        self.horizontalLayout_42.addWidget(self.dataTOFautoMode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem2)
        self.dataTOFmanualMode = QtWidgets.QRadioButton(self.frame_14)
        self.dataTOFmanualMode.setEnabled(False)
        self.dataTOFmanualMode.setAutoExclusive(True)
        self.dataTOFmanualMode.setObjectName(_fromUtf8("dataTOFmanualMode"))
        self.horizontalLayout_42.addWidget(self.dataTOFmanualMode)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_40.addWidget(self.frame_14)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem3)
        self.TOFmanualFromLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TOFmanualFromLabel.setEnabled(False)
        self.TOFmanualFromLabel.setObjectName(_fromUtf8("TOFmanualFromLabel"))
        self.horizontalLayout_40.addWidget(self.TOFmanualFromLabel)
        self.TOFmanualFromValue = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.TOFmanualFromValue.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOFmanualFromValue.sizePolicy().hasHeightForWidth())
        self.TOFmanualFromValue.setSizePolicy(sizePolicy)
        self.TOFmanualFromValue.setMinimumSize(QtCore.QSize(100, 0))
        self.TOFmanualFromValue.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TOFmanualFromValue.setObjectName(_fromUtf8("TOFmanualFromValue"))
        self.horizontalLayout_40.addWidget(self.TOFmanualFromValue)
        self.TOFmanualFromUnitsValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TOFmanualFromUnitsValue.setEnabled(False)
        self.TOFmanualFromUnitsValue.setObjectName(_fromUtf8("TOFmanualFromUnitsValue"))
        self.horizontalLayout_40.addWidget(self.TOFmanualFromUnitsValue)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem4)
        self.TOFmanualToLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TOFmanualToLabel.setEnabled(False)
        self.TOFmanualToLabel.setObjectName(_fromUtf8("TOFmanualToLabel"))
        self.horizontalLayout_40.addWidget(self.TOFmanualToLabel)
        self.TOFmanualToValue = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.TOFmanualToValue.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOFmanualToValue.sizePolicy().hasHeightForWidth())
        self.TOFmanualToValue.setSizePolicy(sizePolicy)
        self.TOFmanualToValue.setMinimumSize(QtCore.QSize(100, 0))
        self.TOFmanualToValue.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TOFmanualToValue.setObjectName(_fromUtf8("TOFmanualToValue"))
        self.horizontalLayout_40.addWidget(self.TOFmanualToValue)
        self.TOFmanualToUnitsValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TOFmanualToUnitsValue.setEnabled(False)
        self.TOFmanualToUnitsValue.setObjectName(_fromUtf8("TOFmanualToUnitsValue"))
        self.horizontalLayout_40.addWidget(self.TOFmanualToUnitsValue)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem5)
        self.forceSortByMetaData = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.forceSortByMetaData.setWhatsThis(_fromUtf8(""))
        self.forceSortByMetaData.setFlat(False)
        self.forceSortByMetaData.setObjectName(_fromUtf8("forceSortByMetaData"))
        self.horizontalLayout_40.addWidget(self.forceSortByMetaData)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_40)
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 350))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(45)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sfFileNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sfFileNameLabel.setObjectName(_fromUtf8("sfFileNameLabel"))
        self.horizontalLayout_3.addWidget(self.sfFileNameLabel)
        self.sfFileNameBrowseButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.sfFileNameBrowseButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sfFileNameBrowseButton.setObjectName(_fromUtf8("sfFileNameBrowseButton"))
        self.horizontalLayout_3.addWidget(self.sfFileNameBrowseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.sfFileNamePreview = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.sfFileNamePreview.setEnabled(False)
        self.sfFileNamePreview.setMinimumSize(QtCore.QSize(0, 60))
        self.sfFileNamePreview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sfFileNamePreview.setObjectName(_fromUtf8("sfFileNamePreview"))
        self.verticalLayout.addWidget(self.sfFileNamePreview)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.generateSFfileButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.generateSFfileButton.setEnabled(False)
        self.generateSFfileButton.setObjectName(_fromUtf8("generateSFfileButton"))
        self.horizontalLayout_4.addWidget(self.generateSFfileButton)
        self.exportButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.exportButton.setEnabled(False)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_4.addWidget(self.exportButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        SFCalculatorInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SFCalculatorInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        SFCalculatorInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SFCalculatorInterface)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SFCalculatorInterface.setStatusBar(self.statusbar)
        self.actionLoadingConfiguration = QtWidgets.QAction(SFCalculatorInterface)
        self.actionLoadingConfiguration.setEnabled(False)
        self.actionLoadingConfiguration.setObjectName(_fromUtf8("actionLoadingConfiguration"))
        self.actionSavingAsConfiguration = QtWidgets.QAction(SFCalculatorInterface)
        self.actionSavingAsConfiguration.setEnabled(False)
        self.actionSavingAsConfiguration.setObjectName(_fromUtf8("actionSavingAsConfiguration"))
        self.actionSavingConfiguration = QtWidgets.QAction(SFCalculatorInterface)
        self.actionSavingConfiguration.setEnabled(False)
        self.actionSavingConfiguration.setObjectName(_fromUtf8("actionSavingConfiguration"))
        self.actionEdit_Incident_Medium_List = QtWidgets.QAction(SFCalculatorInterface)
        self.actionEdit_Incident_Medium_List.setObjectName(_fromUtf8("actionEdit_Incident_Medium_List"))
        self.clearSFconentFileMenu = QtWidgets.QAction(SFCalculatorInterface)
        self.clearSFconentFileMenu.setObjectName(_fromUtf8("clearSFconentFileMenu"))
        self.menuFile.addAction(self.actionLoadingConfiguration)
        self.menuFile.addAction(self.actionSavingAsConfiguration)
        self.menuFile.addAction(self.actionSavingConfiguration)
        self.menuTools.addAction(self.clearSFconentFileMenu)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(SFCalculatorInterface)
        QtCore.QObject.connect(
            self.runSequenceLineEdit,
            QtCore.SIGNAL(_fromUtf8("returnPressed()")),
            SFCalculatorInterface.runSequenceLineEditEvent,
        )
        QtCore.QObject.connect(
            self.tableWidget,
            QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")),
            SFCalculatorInterface.tableWidgetRightClick,
        )
        QtCore.QObject.connect(
            self.sfFileNameBrowseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.browseFile
        )
        QtCore.QObject.connect(
            self.actionSavingAsConfiguration,
            QtCore.SIGNAL(_fromUtf8("triggered()")),
            SFCalculatorInterface.savingAsConfiguration,
        )
        QtCore.QObject.connect(
            self.dataTOFautoMode, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.selectAutoTOF
        )
        QtCore.QObject.connect(
            self.dataTOFmanualMode, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.selectManualTOF
        )
        QtCore.QObject.connect(
            self.actionLoadingConfiguration,
            QtCore.SIGNAL(_fromUtf8("triggered()")),
            SFCalculatorInterface.loadingConfiguration,
        )
        QtCore.QObject.connect(
            self.tableWidget,
            QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")),
            SFCalculatorInterface.tableWidgetCellSelected,
        )
        QtCore.QObject.connect(
            self.dataBackToValue,
            QtCore.SIGNAL(_fromUtf8("editingFinished()")),
            SFCalculatorInterface.back2SpinBoxValueChanged,
        )
        QtCore.QObject.connect(
            self.dataBackFromValue,
            QtCore.SIGNAL(_fromUtf8("editingFinished()")),
            SFCalculatorInterface.back1SpinBoxValueChanged,
        )
        QtCore.QObject.connect(
            self.dataPeakFromValue,
            QtCore.SIGNAL(_fromUtf8("editingFinished()")),
            SFCalculatorInterface.peak1SpinBoxValueChanged,
        )
        QtCore.QObject.connect(
            self.dataPeakToValue,
            QtCore.SIGNAL(_fromUtf8("editingFinished()")),
            SFCalculatorInterface.peak2SpinBoxValueChanged,
        )
        QtCore.QObject.connect(
            self.TOFmanualFromValue,
            QtCore.SIGNAL(_fromUtf8("returnPressed()")),
            SFCalculatorInterface.manualTOFtextFieldValidated,
        )
        QtCore.QObject.connect(
            self.TOFmanualToValue,
            QtCore.SIGNAL(_fromUtf8("returnPressed()")),
            SFCalculatorInterface.manualTOFtextFieldValidated,
        )
        QtCore.QObject.connect(
            self.incidentMediumComboBox,
            QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")),
            SFCalculatorInterface.incidentMediumComboBoxChanged,
        )
        QtCore.QObject.connect(
            self.actionSavingConfiguration,
            QtCore.SIGNAL(_fromUtf8("triggered()")),
            SFCalculatorInterface.savingConfiguration,
        )
        QtCore.QObject.connect(
            self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.editIncidentMediumList
        )
        QtCore.QObject.connect(
            self.generateSFfileButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.generateSFfile
        )
        QtCore.QObject.connect(
            self.exportButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SFCalculatorInterface.exportScript
        )
        QtCore.QObject.connect(
            self.tableWidget,
            QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")),
            SFCalculatorInterface.tableWidgetCellEntered,
        )
        QtCore.QObject.connect(
            self.clearSFconentFileMenu,
            QtCore.SIGNAL(_fromUtf8("triggered()")),
            SFCalculatorInterface.clearSFContentFile,
        )
        QtCore.QObject.connect(
            self.tableWidget,
            QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")),
            SFCalculatorInterface.tableWidgetRowSelected,
        )
        QtCore.QMetaObject.connectSlotsByName(SFCalculatorInterface)

    def retranslateUi(self, SFCalculatorInterface):
        SFCalculatorInterface.setWindowTitle(_translate("SFCalculatorInterface", "SF Calculator", None))
        self.label.setText(_translate("SFCalculatorInterface", "Run or Sequence of Runs:", None))
        self.runSequenceLineEdit.setToolTip(
            _translate("SFCalculatorInterface", "1234 or 1234,1236,1239 or 1234-1238", None)
        )
        self.incidentMediumComboBox.setItemText(
            0, _translate("SFCalculatorInterface", "Select or Define Incident Medium ...", None)
        )
        self.toolButton.setText(_translate("SFCalculatorInterface", "...", None))
        self.error_label.setText(_translate("SFCalculatorInterface", "SELECTION ERROR", None))
        self.dataBackFromLabel.setText(_translate("SFCalculatorInterface", "Back2", None))
        self.back2_error.setText(_translate("SFCalculatorInterface", "*", None))
        self.dataPeakFromLabel.setText(_translate("SFCalculatorInterface", "Peak2", None))
        self.peak2_error.setText(_translate("SFCalculatorInterface", "*", None))
        self.dataPeakToLabel.setText(_translate("SFCalculatorInterface", "Peak1", None))
        self.peak1_error.setText(_translate("SFCalculatorInterface", "*", None))
        self.dataBackToLabel.setText(_translate("SFCalculatorInterface", "Back1", None))
        self.back1_error.setText(_translate("SFCalculatorInterface", "*", None))
        self.dataBackgroundFlag.setText(_translate("SFCalculatorInterface", "with background", None))
        self.dataTOFmanualLabel.setText(_translate("SFCalculatorInterface", "TOF range", None))
        self.dataTOFautoMode.setText(_translate("SFCalculatorInterface", "Auto", None))
        self.dataTOFmanualMode.setText(_translate("SFCalculatorInterface", "Manual", None))
        self.TOFmanualFromLabel.setText(_translate("SFCalculatorInterface", "from", None))
        self.TOFmanualFromValue.setText(_translate("SFCalculatorInterface", "0", None))
        self.TOFmanualFromUnitsValue.setText(_translate("SFCalculatorInterface", "ms", None))
        self.TOFmanualToLabel.setText(_translate("SFCalculatorInterface", "to", None))
        self.TOFmanualToValue.setText(_translate("SFCalculatorInterface", "200", None))
        self.TOFmanualToUnitsValue.setText(_translate("SFCalculatorInterface", "ms", None))
        self.forceSortByMetaData.setText(_translate("SFCalculatorInterface", "sort", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SFCalculatorInterface", "Run #", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SFCalculatorInterface", "Nbr of Attenuators", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SFCalculatorInterface", "lambda min", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SFCalculatorInterface", "lambda max", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SFCalculatorInterface", "p Charge", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SFCalculatorInterface", "lambda Requested", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SFCalculatorInterface", "S1W", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("SFCalculatorInterface", "S1H", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("SFCalculatorInterface", "SiW", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("SFCalculatorInterface", "SiH", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("SFCalculatorInterface", "Peak1", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("SFCalculatorInterface", "Peak2", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("SFCalculatorInterface", "Back1", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("SFCalculatorInterface", "Back2", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("SFCalculatorInterface", "TOF1 (ms)", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("SFCalculatorInterface", "TOF2 (ms)", None))
        self.label_2.setText(_translate("SFCalculatorInterface", "SF File Name:", None))
        self.sfFileNameLabel.setText(_translate("SFCalculatorInterface", "N/A", None))
        self.sfFileNameBrowseButton.setText(_translate("SFCalculatorInterface", "Browse ...", None))
        self.generateSFfileButton.setText(_translate("SFCalculatorInterface", "GENERATE SCALING FACTORS", None))
        self.exportButton.setText(_translate("SFCalculatorInterface", "EXPORT SCRIPT ...", None))
        self.menuFile.setTitle(_translate("SFCalculatorInterface", "Configuration", None))
        self.menuTools.setTitle(_translate("SFCalculatorInterface", "Tools", None))
        self.actionLoadingConfiguration.setText(_translate("SFCalculatorInterface", "Load ...", None))
        self.actionLoadingConfiguration.setShortcut(_translate("SFCalculatorInterface", "Meta+O", None))
        self.actionSavingAsConfiguration.setText(_translate("SFCalculatorInterface", "Save As ...", None))
        self.actionSavingAsConfiguration.setShortcut(_translate("SFCalculatorInterface", "Meta+Shift+S", None))
        self.actionSavingConfiguration.setText(_translate("SFCalculatorInterface", "Save", None))
        self.actionSavingConfiguration.setShortcut(_translate("SFCalculatorInterface", "Meta+S", None))
        self.actionEdit_Incident_Medium_List.setText(
            _translate("SFCalculatorInterface", "Edit Incident Medium List ...", None)
        )
        self.clearSFconentFileMenu.setText(_translate("SFCalculatorInterface", "Clear Content SF File", None))
