name: Trigger ORNL GitLab Production Pipeline
on: 
  push:
    branches:
      - main
      - migrate_travis_to_github_actions
jobs:
  ornl-trigger-main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       include:
         - python-version: 2.7
           env: "prod"
    steps:
      - run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=main ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1.0.7
        name: Setup Conda
        with:
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          activate-conda: true
      - name: Check versions
        run: |
            conda --version
            which python
            python --version
            pwd
            ls
      - name: Install Dependencies
        run: |
            chmod +x ${GITHUB_WORKSPACE}/.github/scripts/install.sh
            ${GITHUB_WORKSPACE}/.github/scripts/install.sh
        env:
          PYTHON_ VERSION: ${{ matrix.python-version }}
      - name: Setup Test Env and Run Tests
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/test.sh
          ${GITHUB_WORKSPACE}/.github/scripts/test.sh
        env:
          PYTHON_ VERSION: ${{ matrix.python-version }}
      - name: Run Codecov
        run: codecov
