name: Trigger ORNL GitLab Production Pipeline
on:
  push:
    branches:
      - main
      - next
      - qa
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        name: Setup Conda
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: .github/workflows/conda_env/environment.yml
      - name: flake8
        run: flake8 --statistics RefRed
      - name: Run Tests
        run: xvfb-run -a python -m pytest --cov=RefRed --cov-report=xml --cov-report=term test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Trigger ORNL GitLab Pipeline for PROD
        if: ${{ github.ref == 'refs/heads/main' }}
        run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=main ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null

      - name: Trigger ORNL GitLab Pipeline for DEV
        if: ${{ github.ref == 'refs/heads/next' }}
        run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=main -F variables[PLAY]=conda/update -F variables[CONDA_ENV]=refred-dev ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null

      - name: Trigger ORNL GitLab Pipeline for QA
        if: ${{ github.ref == 'refs/heads/qa' }}
        run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=main -F variables[PLAY]=conda/update -F variables[CONDA_ENV]=refred-qa ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
