name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: mypy type annotations
        run: pixi run mypy src/refred test

      - name: Unit test with code coverage
        run: pixi run test -vv --cov=refred --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required

  package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Build Conda package
        run: pixi run conda-build

      - name: upload conda package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-conda-package
          path: refred-*.conda

  conda-verify:
    needs: package
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test
          init-shell: bash
          create-args: >-
            python=3.10

      - name: Download conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-conda-package
          path: /tmp/local-channel/linux-64

      - name: Install the package
        run: |
          micromamba install --yes -c conda-forge conda-build conda-index
          python -m conda_index /tmp/local-channel
          micromamba install --yes -c /tmp/local-channel -c mantid-ornl -c conda-forge refred

      - name: Verify the installation
        run: python -c "import refred"
